---
title: "In-class Exercise 5"
---

```{r}
pacman::p_load(tidytext, widyr, wordcloud, DT,
               ggwordcloud, textplot, lubridate,
               hms, tidyverse)
```

```{r}
news20 <- "data/20news/"
```

```{r}
read_folder <- function(infolder){
  tibble(file = dir(infolder,
                    full.names = TRUE)) %>%
    mutate(text=map(file,
                    read_lines)) %>%
    transmute(id = basename(file),
              text) %>%
    unnest(text)
}
```


```{r}
raw_text <- tibble(
  folder = dir(news20,
               full.names = TRUE)) %>%
  mutate(folder_out = map(
    folder,
    read_folder)) %>%
  unnest(cols = c(folder_out)) %>%
  transmute(newsgroup = basename(folder),
            id, text)
```

```{r}
write_rds(raw_text, 
          "data/rds/new20.rds")
```

```{r}
read_rds("data/rds/new20.rds")
```

```{r}
raw_text %>%
  group_by(newsgroup) %>%
  summarise(messages = n_distinct(id)) %>%
  ggplot(aes(messages, newsgroup)) +
  geom_col(fill = "lightblue") +
  labs(y = NULL)
```

```{r}
cleaned_text <- raw_text %>%
  group_by(newsgroup, id) %>%
  filter(cumsum(text == "") > 0,
         cumsum(str_detect(
           text, "^--")) == 0) %>%
  ungroup()
```

```{r}
cleaned_text <- cleaned_text %>%
  filter(str_detect(
    text, "^[^>]+[A-Za-z\\d]")
    |text == "",
    !str_detect(
      text, "writes(:|\\.\\.\\.)$"),
    !str_detect(
      text, "^In article <"
    )
)
```

```{r}
usenet_words <- cleaned_text %>%
  unnest_tokens(word, text) %>%
  filter(str_detect(word, "[a-z']$"))
```
